// data.js — Contenido de cada dia de la semana pedagogica
const STATIONS = {
  d0: { zona:'inicio', nombre:'Introduccion y Justificacion',
    contexto:'Los descansos de primaria como espacios formativos de encuentro, juego y convivencia.',
    enfoque:'Integrar el Aprendizaje Social y Emocional (ASE) al curriculo vivo, no como relleno sino como eje transversal.',
    metodologia:'El descanso se resignifica como un laboratorio pedagogico, con actividades guiadas cada dia de la semana.',
    tics:'—',
    aportes:'Sienta las bases conceptuales de toda la ruta semanal.',
    fuente:null },
  d1: { zona:'lunes', nombre:'Lunes de Ritmo y Escucha',
    contexto:'Responsable: Docente de Musica. Exploracion instrumental, canto y percusion corporal en el patio.',
    enfoque:'Sensibilidad artistica y expresion sonora colectiva.',
    metodologia:'Circulos de ritmo, canciones rondas y percusion con materiales reciclados.',
    tics:'Grabadora de voz para registrar composiciones grupales.',
    aportes:'Fortalece autocontrol, respeto por los turnos y cuidado de instrumentos compartidos.',
    fuente:null },
  d2: { zona:'martes', nombre:'Martes de Memoria Ludica',
    contexto:'Responsable: Docente de Educacion Fisica. Trompo, metras, salto de lazo, golosa.',
    enfoque:'Recuperar la cultura infantil tradicional y la coordinacion motriz.',
    metodologia:'Estaciones rotativas de juegos tradicionales con reglas acordadas por los estudiantes.',
    tics:'—',
    aportes:'Cooperacion, resolucion pacifica de conflictos y motricidad gruesa.',
    fuente:null },
  d3: { zona:'miercoles', nombre:'Miercoles de Estrategia Logica',
    contexto:'Responsable: Docente de Matematicas. Ajedrez, parques, domino, tangram y retos logicos.',
    enfoque:'Pensamiento estrategico y toma de decisiones.',
    metodologia:'Torneos breves por parejas con acompanamiento docente y fichas de registro de jugadas.',
    tics:'Apps de ajedrez para practicar en casa (opcional).',
    aportes:'Paciencia ante la frustracion, atencion sostenida y planificacion.',
    fuente:null },
  d4: { zona:'jueves', nombre:'Jueves de Expresion y Pantallas',
    contexto:'Cine pedagogico en cafeteria y karaoke en el aula virtual.',
    enfoque:'Lectura audiovisual critica y expresion oral.',
    metodologia:'Proyeccion de cortos educativos seguida de dialogo guiado; sesiones de karaoke por grupos.',
    tics:'Proyector, plataforma de streaming educativo, microfono.',
    aportes:'Ciudadania digital, disfrute comunicativo y trabajo en equipo.',
    fuente:null },
  d5: { zona:'viernes', nombre:'Viernes de Movimiento Colectivo',
    contexto:'Responsables: Danzas y Ciencias Sociales. Rumba terapia y expresion corporal dirigida.',
    enfoque:'Bienestar fisico e identidad cultural.',
    metodologia:'Coreografias grupales sencillas con musica regional, cierre semanal simbolico.',
    tics:'Parlante bluetooth, listas de reproduccion colaborativas.',
    aportes:'Integracion grupal y estado de flow (disfrute profundo) para cerrar la semana.',
    fuente:null },
  d6: { zona:'final', nombre:'Mision Cumplida: Laboratorio de Ciudadania',
    contexto:'Conclusiones y evaluacion formativa de la semana.',
    enfoque:'El descanso como tiempo educativo protegido.',
    metodologia:'Evaluacion cualitativa en 5 dimensiones: Participacion, Convivencia, Autonomia, Creatividad y Cuidado Institucional.',
    tics:'—',
    aportes:'Un curriculo mas humano, sensible e inclusivo, con multiples vias de participacion.',
    fuente:null }
};

const DAY_ORDER = ['d0','d1','d2','d3','d4','d5','d6'];
